version: '3'
networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
    php:
        networks:
          frontend:
            ipv4_address: 172.20.0.2
        container_name: ${APP_NAME}_php
        image: ${APP_NAME}_php
        build:
            context: ./etc/php
            args:
              USER_ID: ${USER_ID:-0}
              GROUP_ID: ${GROUP_ID:-0}
        volumes:
            - ${APP_PATH}:/usr/share/nginx/html
            - "./etc/php/php.ini:/usr/local/etc/php/php.ini"
        links:
            - database:mysqldb
        #restart: always
        environment:
            - COLUMNS
            - LINES
            - TERM
            - XDEBUG_CONFIG=${XDEBUG_CONFIG}
    database:
      networks:
        frontend:
          ipv4_address: 172.20.0.3
      image: mysql:8
      command: --default-authentication-plugin=mysql_native_password
      container_name: ${APP_NAME}_mysql
      environment:
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ports:
          - ${PORT_DATABASE}:3306
      volumes:
          - "./data/db/mysql:/var/lib/mysql"
          - "./etc/mysql:/etc/mysql/conf.d"
    web:
      networks:
        frontend:
          ipv4_address: 172.20.0.4
      container_name: ${APP_NAME}_nginx
      image: nginx:1.18
      ports:
        - ${PORT_HTTP}:80
      links:
        - php
      volumes:
        - ${APP_PATH}:/usr/share/nginx/html
        - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    myadmin:
      networks:
        frontend:
          ipv4_address: 172.20.0.5
      image: phpmyadmin/phpmyadmin
      container_name: ${APP_NAME}_phpmyadmin
      ports:
        - ${PORT_PHPMYADMIN}:80
      restart: always
      links:
        - database:db
      depends_on:
        - database
    mailcatcher:
      networks:
        frontend:
          ipv4_address: 172.20.0.6
      image: schickling/mailcatcher
      container_name: ${APP_NAME}_mailcatcher
      ports:
        - ${PORT_MAILCATCHER}:1080